version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: issue-service:local
  dev:
    image: issue-service:local
    volumes:
      - $HOME/.m2:/root/.m2
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: secret
      DB_NAME: demo
    ports:
      - 9100:8080
    depends_on:
      - db
  test:
    image: issue-service:local
    volumes:
      - $HOME/.m2:/root/.m2
    working_dir: /app
    command: sh -c "./mvnw test"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: secret
      DB_NAME: demo
    depends_on:
      - db
  db:
    image: postgres:11.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: demo
