version: "3.7"

services:
  db:
    image: postgres:11.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: demo
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
