spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          # Fix start up exception:
          # java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
          # Reference:
          # https://github.com/spring-projects/spring-boot/issues/12374
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: false
    show-sql: true
